#!/bin/zsh

_shell_config_repo_root() {
  local src="${(%):-%x}"
  while [[ -L "$src" ]]; do
    local dir
    dir=$(cd -P "$(dirname "$src")" && pwd)
    src=$(readlink "$src")
    if [[ $src != /* ]]; then
      src="$dir/$src"
    fi
  done
  cd -P "$(dirname "$src")/.." && pwd
}

__shell_config_root="$(_shell_config_repo_root)"
export UTILS_REPO_PATH="$__shell_config_root"

source "$__shell_config_root"/shared/textFormatting.sh
source "$__shell_config_root"/shared/common.sh
source "$__shell_config_root"/shared/lazy.sh
source "$__shell_config_root"/shared/path.sh
source "$__shell_config_root"/shared/macOS.sh
source "$__shell_config_root"/shared/git.sh
source "$__shell_config_root"/shared/system.sh
source "$__shell_config_root"/shared/gpt.sh

if [[ -e "$__shell_config_root/local/private.sh" ]]; then
  source "$__shell_config_root/local/private.sh"
elif [[ -e "$HOME"/bash_utils/private.sh ]]; then
  source "$HOME"/bash_utils/private.sh
fi

autoload -Uz compinit
compinit -i

setopt AUTO_MENU
setopt COMPLETE_IN_WORD

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' rehash true

if [[ -f "$HOME/.antidote/antidote.zsh" ]] && [[ -f "$__shell_config_root/zsh/plugins.txt" ]]; then
  source "$HOME/.antidote/antidote.zsh"
  antidote load "$__shell_config_root/zsh/plugins.txt"
fi

autoload -Uz vcs_info
zstyle ':vcs_info:git:*' formats '%b'

_update_vcs_prompt() {
  local branch max_branch_len truncated_branch
  vcs_info
  branch=${vcs_info_msg_0_:-}
  if [[ -z "$branch" ]]; then
    __shell_branch_prompt=""
    return 0
  fi

  max_branch_len=24
  truncated_branch=$branch
  if (( ${#branch} > max_branch_len )); then
    truncated_branch="${branch[1,max_branch_len-3]}..."
  fi

  __shell_branch_prompt=" %F{white}>%f %F{green}${truncated_branch}%f"
}

precmd_functions+=( _update_vcs_prompt )

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search
bindkey '^P' up-line-or-beginning-search
bindkey '^N' down-line-or-beginning-search

setopt PROMPT_SUBST
PROMPT='%F{blue}%~%f${__shell_branch_prompt} %# '

unset -f _shell_config_repo_root
unset __shell_config_root
